[[bin]]
path="./bin/stcc.rs"
name="stcc"

[lib]
path="./lexer.rs"

[package]
name = "stcc"
version = "0.1.0"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "1.0.5"